In [133]:
!pip install jovian --upgrade --quiet
!pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [134]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [135]:
import torch.nn as nn

In [136]:
inputs = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], 
                   [10, 11, 12], [13, 14, 15], [16, 17, 18], 
                   [19, 20, 21], [22, 23, 24], [25, 26, 27], 
                   [28, 29, 30], [31, 32, 33], [34, 35, 36], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [137]:
inputs

tensor([[  1.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.],
        [ 10.,  11.,  12.],
        [ 13.,  14.,  15.],
        [ 16.,  17.,  18.],
        [ 19.,  20.,  21.],
        [ 22.,  23.,  24.],
        [ 25.,  26.,  27.],
        [ 28.,  29.,  30.],
        [ 31.,  32.,  33.],
        [ 34.,  35.,  36.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [138]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [139]:
from torch.utils.data import TensorDataset

In [140]:
#you can list it 1,2,3 there is a 0 too
#the : is from x to y x:y
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [141]:
from torch.utils.data import DataLoader

In [142]:
#defining the dataloader
#the data loader can slpit the data into batches while training.It can also shuffle and random sampling the data
batch_size=5
train_dl= DataLoader(train_ds,batch_size,shuffle=True)

In [143]:
#the shuffleing is taking the batch[]you choose and shuffling it based on the amount on each batch.
#train_ds is all of the input and targets batch size is how many [] in each batch and shuffle is shuffling together
for xb,yb in train_dl:
    print(xb)
    print(yb)

tensor([[102.,  43.,  37.],
        [ 10.,  11.,  12.],
        [ 69.,  96.,  70.],
        [ 28.,  29.,  30.],
        [  4.,   5.,   6.]])
tensor([[ 22.,  37.],
        [ 22.,  37.],
        [103., 119.],
        [103., 119.],
        [ 81., 101.]])
tensor([[34., 35., 36.],
        [13., 14., 15.],
        [19., 20., 21.],
        [25., 26., 27.],
        [ 7.,  8.,  9.]])
tensor([[ 81., 101.],
        [103., 119.],
        [ 81., 101.],
        [ 22.,  37.],
        [119., 133.]])
tensor([[ 22.,  23.,  24.],
        [ 87., 134.,  58.],
        [ 31.,  32.,  33.],
        [ 16.,  17.,  18.],
        [  1.,   2.,   3.]])
tensor([[119., 133.],
        [119., 133.],
        [ 56.,  70.],
        [ 56.,  70.],
        [ 56.,  70.]])


In [144]:
#the bias weights and bias determines if the neuron in the next layer is activated.Indicates how strong of the connection
#is between two nerons in seperate layers
#The bias is constant and the weight is constanlty changing
#a high weight will transfer to the enxt neron and a low weight will not
#the bias is another hidden layer you add to the final weights
#cloums then rows
#nice syntax for generating weights and biases these are the things we adjust to our model to make it better
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5612, -0.4916, -0.0431],
        [ 0.1227,  0.1007,  0.1877]], requires_grad=True)
Parameter containing:
tensor([-0.3763, -0.1804], requires_grad=True)


In [145]:
preds=model(inputs)
preds

tensor([[  -2.0501,    0.7068],
        [  -5.3381,    1.9400],
        [  -8.6261,    3.1733],
        [ -11.9141,    4.4065],
        [ -15.2020,    5.6398],
        [ -18.4900,    6.8731],
        [ -21.7780,    8.1063],
        [ -25.0659,    9.3396],
        [ -28.3539,   10.5729],
        [ -31.6419,   11.8061],
        [ -34.9299,   13.0394],
        [ -38.2178,   14.2727],
        [-117.5847,   34.8728],
        [ -80.3585,   23.6087],
        [ -89.3171,   31.0909]], grad_fn=<AddmmBackward>)

In [146]:
#this is the nice syntax for the loss function 
import torch.nn.functional as f

In [147]:
loss_fn=f.mse_loss

In [148]:
loss=loss_fn(preds,targets)
print(loss)

tensor(11315.3916, grad_fn=<MseLossBackward>)


In [149]:
#this is better syntax for optimizing the biases and wieghts
#the model is from defined previoulsy already as the weights and biases 
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [150]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    for epoch in range(num_epochs):
        
        for xb,yb in train_dl:
            preds=model(xb)
            loss=loss_fn(preds,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [155]:
fit(100, model, loss_fn, opt,train_dl)

Epoch [10/100], Loss: 1312.7859
Epoch [20/100], Loss: 2179.6992
Epoch [30/100], Loss: 3226.3923
Epoch [40/100], Loss: 1357.3745
Epoch [50/100], Loss: 1526.5081
Epoch [60/100], Loss: 1197.8513
Epoch [70/100], Loss: 1977.9055
Epoch [80/100], Loss: 2293.2727
Epoch [90/100], Loss: 1466.1487
Epoch [100/100], Loss: 2244.7007


In [159]:
preds=model(inputs)
print(preds)

tensor([[  8.9072,  10.8754],
        [ 15.7539,  19.1435],
        [ 22.6006,  27.4116],
        [ 29.4473,  35.6796],
        [ 36.2941,  43.9477],
        [ 43.1408,  52.2158],
        [ 49.9875,  60.4838],
        [ 56.8342,  68.7519],
        [ 63.6810,  77.0200],
        [ 70.5277,  85.2880],
        [ 77.3744,  93.5561],
        [ 84.2211, 101.8242],
        [102.4057, 113.6888],
        [ 28.0691,  44.7594],
        [159.1264, 186.9462]], grad_fn=<AddmmBackward>)


In [161]:
print(model.weight)

Parameter containing:
tensor([[-0.8651, -0.0676,  3.2150],
        [-0.8630, -0.2859,  3.9049]], requires_grad=True)


In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
